[package]
name = "basic_app"
version = "0.1.0"
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nannou.workspace = true

[[bin]]
name = "hello"
path = "src/hello.rs"
